"""create message table

Revision ID: 063aff5daf98
Revises: 6c8fba5537db
Create Date: 2022-11-28 17:36:41.972206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063aff5daf98'
down_revision = '6c8fba5537db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_msg', sa.Text(), nullable=False),
    sa.Column('bot_response', sa.Text(), nullable=False),
    sa.Column('user_timestamp', sa.DateTime(), nullable=True),
    sa.Column('bot_timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
