"""update tokenblocklist table

Revision ID: 8564e7111bb7
Revises: 7b9d79a86682
Create Date: 2022-12-05 06:40:38.118469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8564e7111bb7'
down_revision = '7b9d79a86682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_constraint('token_blocklist_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('token_blocklist_ibfk_1', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
